name: CI - Build and Push Docker Image

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}
  
  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: CarlosEdu20/hello-manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update image tag in deployment
        run: |
          sed -i 's|image: .*/hello-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}|' deployment.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5 
        with:
          token: ${{ secrets.GH_PAT }} 
          commit-message: "Update image to ${{ github.sha }}"
          title: "Update image to ${{ github.sha }}"
          body: "Automated image update by GitHub Actions."
          branch: "update-image-${{ github.sha }}"
          base: "main"
